[package]
name = "rdcm"
version = "0.1.0"
edition = "2024"

[dependencies]

# For parsing command line arguements
clap = { 
    version = "4.6.4", 
    features = ["derive"] 
}

# An asynchronus Rust client for interacting with the Docker API
bollard = "0.21.0"

# An asynchronus runtime for Rust
tokio = {
    version = "1.53.1",
    features = ["full"]
}

#______________________________________________________________________________

# To be added:


# Common utilities and extension traits for the futures-rs library.
# 3. futures-util = "0.3.33"

#______________________________________________________________________________
